### ISSUE TITLE
Empty sender mail subject won't prevent sender mail

### ISSUE THREAD

**Issue by jpmschuler** [in2code-de/powermail#821] opened 2022-11-02 13:35 UTC
rels  #611

After switching from 10LTS/powermail:^8 to 11LTS/powermail:^10 everything works, except one type of forms where editors created anonymous feedback forms. 
So these don't have a field email, although in general sender email is activated via TypoScript. The editors up until now used the proclaimed feature of the plugin flexform field `settings.flexform.sender.subject` which reads `Subject for Email to Sender (Empty subject disables mail)`- so they just left the subject empty to prevent those mails.

After switching to 11LTS/powermail:^10 these forms instead generate a 503
`
[CRITICAL] request="5a6facc768fee" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": 
Core: Exception handler (WEB: FE): Error, code #0, file /private/typo3conf/ext/powermail/Classes/Domain/Repository/MailRepository.php, line 393: 
Class 'In2code\Powermail\Domain\Repository\ObjectUtility' not found - {"mode":"WEB","application_mode":"FE","exception_class":"Error","exception_code":0,"file":"/private/typo3conf/ext/powermail/Classes/Domain/Repository/MailRepository.php","line":393,"message":"Class 'In2code\\Powermail\\Domain\\Repository\\ObjectUtility' not found","request_url":"https://www.example.com/feedback/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=d13eb5db7b92edada83b604719c4b935","exception":null}
`

While the exception seems not obvious, overriding the page TypoScript with `plugin.tx_powermail.settings.setup.sender.enable = 0` immediately restores previous behaviour, showing the success message, instead of 503; thus it seems that the decision to have an empty flexform field is not respected anymore.

**Comment by mschwemer** [comment] 2024-09-12 17:26
Thanks for the issue. 

The problem is exactly the same as with the receiver stuff in #611. 

I will fix together in one commit.

**Comment by mschwemer** [comment] 2024-09-25 15:54
Fixed today. Will be in the next powermail bugfix release. See #611 and related commit

**Closed by mschwemer** 2024-09-25 15:54 UTC
Labels: bug
