### ISSUE TITLE
Multipage Forms cause Javascript Error

### ISSUE THREAD

**Issue by Bearfect777** [in2code-de/powermail#806] opened 2022-09-05 11:14 UTC
Hello guys,
I have encountered a javascript error when using a multi-page Powermail form.
It looks like it only occurs when you use the "next" or "prev" button at the bottom - to recreate the situation, just go back and forth in the form. So it is random whether a user can fill out the form or gets the error.
When the error occurs, the next page is simply not displayed, but you can then navigate again using the top menu.
If you use the "page 1, page 2, ..." menu, this error does not occur.
Here is the error code

`Uncaught TypeError: Cannot read properties of undefined (reading 'style')
    at Function.value (Form.min.js?1660651425:1:2827)
    at m.showFieldset (Form.min.js?1660651425:1:3109)
    at HTMLButtonElement.<anonymous> (Form.min.js?1660651425:1:3495)`

hope this is usefull and can be fixed easily.

**Comment by einpraegsam** [comment] 2022-09-05 12:02
Can you please specify the TYPO3 and powermail version?

**Comment by Bearfect777** [comment] 2022-09-08 08:14
typo3 version: 11.5.14
powermail version: 10.4.2

**Comment by einpraegsam** [comment] 2022-09-09 20:32
I just tested my test form with various kind of fields and 3 steps. I can switch between page left and right without any error. Any hints how to reproduce this?

**Comment by Bearfect777** [comment] 2022-09-14 10:53
It's totally wild. On my Mac under Chrome it doesn't really occur anymore since I updated everything (typo3 and powermail) but my colleague said it still occurs with her.
Because I thought it might have something to do with the cache, I tested it on devices and browsers with which I have never been on the site. 
Android smartphone Chrome and Firefox and iPad Pro Chrome. There the behavior occurs very often. Maybe you can reproduce it with the mobile devices.

**Comment by mschwemer** [comment] 2024-08-09 15:06
Closing it, since it is an issue with custom partials.

**Closed by mschwemer** 2024-08-09 15:06 UTC
