### ISSUE TITLE
no translation files on crowdin anymore?

### ISSUE THREAD

**Issue by medarob** [in2code-de/powermail#1003] opened 2024-03-22 06:01 UTC
Just wanted to correct a translation when I noticed that there are no translation files anymore on crowdln for this project.

![grafik](https://github.com/in2code-de/powermail/assets/33951787/6f192cf7-0e49-4e11-a392-69ab5542cf77)

**Comment by mschwemer** [comment] 2024-05-08 14:53
I am currently investigating the issue and will fix it the next days.

Probably it's due to the switch of the default branch from `develop` to `master`

**Comment by chrissonntag** [comment] 2024-05-16 08:02
Hi there, as of now the problem still exists. Is there an ETA on when this issue will be fixed?

**Comment by mschwemer** [comment] 2024-05-21 08:59
@chrissonntag I hope to fix it this week. 

Crowdin is somewhat magical to me, esp. if it comes to necessary changes in the settings. I would be happy about any help. :-)

**Comment by medarob** [comment] 2024-05-21 11:52
Have you tried to upload the files with the translations again?

You can upload each files:
![grafik](https://github.com/in2code-de/powermail/assets/33951787/6af20e63-1d38-44d0-8cd1-5e8eaa6abc3e)

Shouldn't that make the translations available again?
Just make sure there are not different branches like `main`, `master` or `develop` in crowdIn available.

Multiple branches leads also to an error. See here: https://typo3.slack.com/archives/C83T6DEKY/p1711546096604939
Fix: https://github.com/derhansen/sf_event_mgt/issues/1217

**Comment by mschwemer** [comment] 2024-05-22 09:21
@medarob Thx for your hints. 

There is only one branch in Crowdin configured. 
Tried to upload the translations in multiple ways (https://typo3.slack.com/archives/CM9DSMMPC/p1716367965566359) 

Now I need to wait for the crowdin support.

**Comment by mschwemer** [comment] 2024-05-24 14:18
No answer yet. 

But finally, I made some progress. :-) 

There is a small difference in the originally translated files and the new ones. The attribute `original` does not match in the xlf files. The old translation files state `original="messages"`. The new ones via the file preview use `original="EXT:powermail/Resources/Private/Language/locallang.xlf"`. 

If I change this attribute and upload the translated files, the import works. Edit and re-upload the files. 

So it is "just" a bunch of manual work to do. 

I will keep you updated.

**Comment by mschwemer** [comment] 2024-05-25 16:09
Puuh ... what a hassle. 

The last message was true for the german language files. 

For all other languages I had to checkout the repo in order find out the most recent translations. I uploaded all languages manually again. I see that the builds were done in the activity tab of crowdin. So I expect them to be available soon via the language update. 

Please give feedback in any case: if it works for you or not.

**Comment by nebrot** [comment] 2024-05-27 06:22
I checked german language and now it's working again in a simple form (TYPO3 12.4.15 + Powermail 12.3.1), it's not empty anymore, thx👍

**Comment by de-hw-as** [comment] 2024-05-27 06:32
I can confirm german language is back (TYPO3 11.5 + Powermail 10.8.1)

**Comment by kitzberger** [comment] 2024-05-27 06:50
Translations for T11/P10 are back again, thanks!

**Comment by medarob** [comment] 2024-05-27 06:56
Thank you. :)

So, editing the files and suggestions for changes will go through CrowdIn now? I think that will make it easier for people to contribute to the language files.

**Comment by thomasrawiel** [comment] 2024-05-27 10:07
Can confirm, the language files for german are correctly updated (v12)

**Closed** 2024-05-28 09:01 UTC
Labels: under investigation, translation

**Comment by chrissonntag** [comment] 2024-06-03 13:21
Can also confirm that all german translation are back. Thanks a lot for your efforts!
