### ISSUE TITLE
[10.8.1] Language files of the German translation are empty

### ISSUE THREAD

**Issue by de-hw-as** [in2code-de/powermail#1032] opened 2024-05-22 14:46 UTC
We use Powermail 10.8.1 under TYPO3 11.5.
The language files are downloaded via TYPO3.
The German language files do not contain any entries.

**Comment by MKupi** [comment] 2024-05-23 07:58
This is under investigation, see #1003

**Comment by mschwemer** [comment] 2024-06-07 08:44
Duplicate of #1003 

Already solved.

**Closed by mschwemer** 2024-06-07 08:44 UTC
