### ISSUE TITLE
Problem when updating from powermail 12.3.1 to 12.3.2

### ISSUE THREAD

**Issue by Typine3** [in2code-de/powermail#1040] opened 2024-06-02 12:48 UTC
12.3.1 ist working as usual, when updating to 12.3.2 i get
Oops, an error occurred! Code: 2024060214372884f41809
when sending a form. No answer page shown, no emails sent.
No more information though i activated debug mode.

**Comment by vnc-jboe** [comment] 2024-06-03 09:13
#1024

**Comment by mschwemer** [comment] 2024-06-07 07:08
Duplicate of #1024 

Fixed in 12.3.4

**Closed by mschwemer** 2024-06-07 07:08 UTC
